= Ethernet

== Hvad Ethernet?
1. https://www.youtube.com/watch?v=5u52wbqBgEY
1. https://www.youtube.com/watch?v=HLziLmaYsO0

== Hvad er Internet Protokollen?
https://www.youtube.com/watch?v=mm-NHrLtRWI


== Målet for idag

Forbind en PC til en Microchip Jaguar2 switch og download firmware til switchen,
så den kan starte Linux op.

Derefter skal du sende et "ping" fra PCen til switchen, og den anden vej, og se hvad der
sker på netværket med programmet WireShark.

=== Kabling
Forbind Jaguar 2 switchen med PCn:

* Netværkskabel
* Serielforbindelses kabel

En serielforbindelse er en måde at forbinde to devices så de kan kommunikere
"tekst".

=== Tænd for Jaguar2 switchen

Start en terminal på PCen (Terminator)

Start termhub programmet inde i terminalen:

----
termhub -d /dev/ttyUSB0
----

Nu er du i en terminal session via USB0 porten og serielforbindelseskablet til
Jaguar2 switchens console port, hvor man kan give kommandoer.

Når switchen starter op vil det være switchens bootloader program der kører
allerførst, og det vil forsøge at finde en applikation at køre.
Hvis den ikke finder nogen så venter den på at få kommandoer.

=== Byg firmware til Jaguar2 switchen

* Start en ny terminal
----
cd src/mesa
----

* Lav et "Little Endian MIPS project"

----
.cmake/create_cmake_project.rb mipsel
----

* Konfiguration af Jaguar2 i CMAKE projektet
Jaguar2 har produktnavnet vsc7468

----
cd build-mipsel
ccmake ..
----

* Tryk på C for "configuration"
* Vælg mfi_vsc7468_pcnt29_ts og tryk på SPACE så der står ON

Dette er en Jaguar2 med 29 porte og timestamping der bliver valgt.

* Tryk på C igen for at gå ud af konfigurationen
* Tryk på G for "Generate and leave"  Dette opretter configurationen.
* Byg firmwaren

----
make -j 8 
----

Dette bygger en mfi_vsc7468_pcnt29_ts.mfi fil som er en Microchip Firmware Image
fil, som indeholder flere ting:

* En Linux Kerne
* En konfiguration (Device Tree)
* Et filesystem (Root filesystem)

Denne fil skal nu fra PCen over på Jaguar2, og det gør vi i bootloaderen
ved at:

På PCen lægger vi MFI filen i en bestemt folder som vores WebServer på
PCen kender:

----
cp mesa/demo/mfi_vsc7468_pcnt29_ts.mfi /tftpboot/
----

Check dette med browseren
* Start Chrome
* Vælg adressen http://localhost
* Check at der er en mfi_vsc7468_pcnt29_ts.mfi fil

Skift til termhub terminalen
Tast ? så du kan se bootloaderens menu

----
?
----

Hent Jaguar2s firmware over i bootloaderens memory:

----
dhcp mfi_vsc7468_pcnt29_ts.mfi
----

Start den nye firmware

----
bootmfi
----

Login i linux med brugernavnet "root"

----
root
----

Start mesa-demo programmet

----
mesa-demo
----

Check hvilke netværksinterfaces der findes på Jarguar2 switchen nu:

----
ip a
----

Ikke særlig mange, og ikke de rigtige.  Prøv at finde ud af hvilke frontporte
der er netværkstrafik på:

----
mesa-cmd port state
----
Noter den port som der er trafik på ned, og genstart i bootloaderen.

----
reboot
----

Gentag processen fra før men denne gang starter vi mesa-demo applikationen med
den port som vi så trafik på (x).
----
mesa-demo -p x
----
Prøv nu at checke hvilke interfaces der er i Linux:

----
ip a
----

Nu er der oprettet et interface på den port vi kunne se trafik på (den som er
forbundet til PCen.

Giv nu porten en IP adresse som passer til det netværk den sidder på.

Start en ny terminal og check netværksinterfaces på PCen.  Der er et par
stykker.  Find det der hedder eth_mgmt.
Check dets IP adresse.  Den ser sådan ud:

----
inet 10.99.y.1/zz brd 10.99.y.255 scope global eth_mgmt
----

Noter 10.99.y.1/zz delen ned.  Den skal vi bruge.

I termhub terminalen giver vi nu en matchende adresse til Jaguar2 switchens
netværksinterface.

----
ip addr add 10.99.y.2/zz dev vtss.port.x
----

Nu har netværksinterfacet vtss.port.x som er forbundet til front port x fået en
IP adresse, så den kan sende og modtage IP pakker.

Pointen er at PCens adresse slutter på .1 og switchens på .2, så de har
altså forskellige adresser men er på samme netværk, så de har mulighed for at
kommunikere med hinanden.

Send 5 ping pakker fra Jaguar 2 til PCen

----
ping -c 5 10.99.y.1
----

Check at dette gik godt.  Der skulle gerne stå sådan her: "0% packet loss"

----
--- 10.99.y.1 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 1.094/1.249/1.863 ms
----

Send 5 ping pakker fra PCen til Jaguar2 switchen

----
ping -c 5 10.99.y.2
----

Prøv nu at starte *WireShark* programmet på PCen og lyt på *eth_mgmt*
netværksinterfacet.

Send ping pakker i en lind strøm fra Jaguar2 til PCen.

----
ping 10.99.y.1
----

== Opgaver

1. Hvad hedder disse pakker i WireShark?
1. Hvad indeholder de?
1. Hvad er MAC adresserne på de to devices?
1. Hvilke andre pakker kan du se på dette netværk?

